#ifndef _SPIDER3D_H

#define _SPIDER3D_H


#include "Node.h"
#include "NodeAnimator.h"
#include "TransformAnimator.h"
#include "ColorAnimator.h"
#include "TransparencyAnimator.h"
#include "RotationAnimator.h"
#include "ScaleAnimator.h"
#include "PositionAnimator.h"
#include "OrbitalCameraAnimator.h"
#include "FpsCameraAnimator.h"
#include "SkyBoxNode.h"
#include "CameraNode.h"
#include "LightNode.h"
#include "MeshNode.h"
#include "MeshBuffer.h"
#include "IndexedMeshBuffer.h"
#include "SMeshBuffer.h"
#include "SIndexedMeshBuffer.h"
#include "Mesh.h"
#include "SceneManager.h"
#include "spiderDisplay.h"
#include "spiderWin32Display.h"
#include "spiderDisplayParams.h"
#include "PrimitiveFactory.h"
#include "STimer.h"
#include "EventListener.h"
#include "Plane.h"
#include "Rectangle.h"
#include "SViewFrustum.h"
#include "Material.h"
#include "PolygonAttributes.h"
#include "TransparencyAttributes.h"
#include "TextureAttributes.h"
#include "TexCoordGeneration.h"
#include "Image.h"
#include "Texture.h"
#include "Texture2D.h"
#include "TexturePointSprite.h"
#include "TextureCubeMap.h"
#include "TextureUnitState.h"
#include "FileLoader.h"
#include "PointAttributes.h"
#include "LineAttributes.h"
#include "ColoringAttributes.h"
#include "DepthAttributes.h"
#include "StencilAttributes.h"
#include "Appearance.h"
#include "ShaderAppearance.h"
#include "ShaderProgram.h"
#include "GLSLShaderProgram.h"
#include "CGShaderProgram.h"
#include "Shader.h"
#include "SourceCodeShader.h"
#include "Cursor.h"
#include "TextureProjector.h"
#include "LightMap.h"
#include "TextureProjectorNode.h"
#include "MeshBufferUpdater.h"
#include "cad.h"
#include "Quaternion.h"
#include "EnvironmentMapGenerator.h"
#include "BillBoard.h"
#include "ParticleBase.h"
#include "ParticleNode.h"
#include "Octree.h"
#include "TpsCameraAnimator.h"
#include "ThirdPersonController.h"
#include "TBNGenerator.h"
#include "NormalMapGenerator.h"
#include "LightMapFace.h"

namespace spider3d
{

SpiderDisplay* createDisplay( RENDERER_TYPE, const sf32 ,const sf32 , su32 , sbool , sbool);

}

#endif 