#ifndef _CHUNKS_3DS_H

#define _CHUNKS_3DS_H

#include "Chunk.h"
#include "AxisChunk.h"
#include "BooleanChunk.h"
#include "BoundingBoxChunk.h"
#include "CameraChunk.h"
#include "CameraTargetInfoChunk.h"
#include "CameraInfoChunk.h"
#include "ColorChunk.h"
#include "FacesMaterialChunk.h"
#include "FloatChunk.h"
#include "FramesChunk.h"
#include "FacesDescriptionChunk.h"
#include "FramesDescriptionChunk.h"
#include "GlobalColorChunk.h"
#include "HierarchyInfoChunk.h"
#include "HotSpotChunk.h"
#include "KFVersionChunk.h"
#include "KeyFramerInfoChunk.h"
#include "LightChunk.h"
#include "MaterialChunk.h"
#include "NameObjVisibilityChunk.h"
#include "NamedObjectChunk.h"
#include "ObjectDummyNameChunk.h"
#include "OmniLightInfoChunk.h"
#include "PercentageChunk.h"
#include "PivotChunk.h"
#include "PolygonModeChunk.h"
#include "PositionChunk.h"
#include "RotationChunk.h"
#include "ScaleChunk.h"
#include "SmoothingChunk.h"
#include "SpotLightChunk.h"
#include "SpotLightInfo.h"
#include "SpotLightTargetInfo.h"
#include "StringChunk.h"
#include "TargetDescriptionChunk.h"
#include "TextureChunk.h"
#include "Vertex2ListChunk.h"
#include "Vertex3ListChunk.h"


#endif